### ISSUE TITLE
Release version 1.2.0

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/PHPCSDevTools#112]
The current `develop` branch contains quite some changes, some which are ready (overdue) for release, others which aren't ready for release yet.

### Ready for release
* PHPCS Docs XSD and everything related to that, see #80.
* Debug sniff whitespace visualization changes.
* Some minor tweaks/bugfixes for the FeatureComplete tool.

### Not ready for release
* Refactor of the FeatureComplete tool.
    There are still some issues with:
    * The use of `STDOUT` vs `STDERR`.
    * The `exclude` feature not working well enough.

As what is _ready for release_ is valuable to get out there, I'm cherrypicking those commits into the `stable` branch and adding the changelog and such to allow for a release.
All cherrypicked PRs have been re-milestoned to `1.2.0`.

As this means I will be pushing the cherrypicked commits and the changelog directly to `stable`, I'm opening this issue to document the release steps.

## Release checklist:
- [x] Update the version number in the `VERSION` file. 
- [x] Add changelog for 1.2.0.
- [ ] ~~Merge this PR~~
- [x] Add release tag against `stable` (careful, GH defaults to `develop`!) & copy & paste the changelog to it
- [x] Close the milestone
- [x] Open a new milestone for the next release
- [x] If any open PRs/issues which were milestoned for this release did not make it into the release, update their milestone. _(not applicable)_
- [ ] Tweet about the release.
- [x] ~~Fast-forward `develop` to `stable` & push it.~~ Back-merge `stable` to `develop` & push it.
